### ISSUE TITLE
Progress Thru Processors (clientscr/progress)

### ISSUE THREAD

**Issue by romw** [nicolas17/boinc2git#6]
We need the pre-compiled binaries from clientscr/progress/win for InstallShield to properly build the Progress Thru Processors setup package.

**Comment by nicolas17** [comment]
I disagree with having these precompiled binaries in version control. They should get built from source like everything else. And if we don't have the sources, that's a problem in itself.

However, strictly from the git-conversion aspect: I just checked that these binaries (including changes in the 6.8 branch) need less than 1.5MB of repository space, so it's certainly possible to put them into the boinc.git repo.
